//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_shooter : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean shoot
        {
            get
            {
                return SteamVR_Actions.shooter_shoot;
            }
        }
        
        public virtual SteamVR_Action_Boolean teleport
        {
            get
            {
                return SteamVR_Actions.shooter_teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean snapLeft
        {
            get
            {
                return SteamVR_Actions.shooter_snapLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean snapRight
        {
            get
            {
                return SteamVR_Actions.shooter_snapRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean grabGrip
        {
            get
            {
                return SteamVR_Actions.shooter_grabGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean grabPinch
        {
            get
            {
                return SteamVR_Actions.shooter_grabPinch;
            }
        }
        
        public virtual SteamVR_Action_Vibration haptic
        {
            get
            {
                return SteamVR_Actions.shooter_haptic;
            }
        }
    }
}
